# Generated by Django 4.1.7 on 2023-02-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pathways/files/photos')),
                ('left', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backLeft', to='images.photo')),
            ],
        ),
    ]
