# Generated by Django 4.1.7 on 2023-02-21 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_photo_down_photo_right_photo_up_alter_photo_left'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='down',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backUp', to='images.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backRight', to='images.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backLeft', to='images.photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='up',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backDown', to='images.photo'),
        ),
    ]
