# Generated by Django 4.1.7 on 2023-02-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_photo_down_alter_photo_left_alter_photo_right_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
