# Generated by Django 4.1.7 on 2023-02-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_photo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.photo')),
            ],
        ),
    ]
