# Generated by Django 4.1.7 on 2023-02-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='Image',
        ),
    ]
