# Generated by Django 4.1.7 on 2023-02-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/images'),
        ),
    ]
