# Generated by Django 4.1.7 on 2023-03-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_path_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='image',
            field=models.ImageField(default='files/images/blank.png', upload_to='files/images'),
        ),
    ]
